# Generated by Django 5.0.6 on 2024-07-18 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_comment_commented_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_name', to='snippets.snippet', verbose_name='スニペット名'),
        ),
    ]
